# Describes the format for available virtual services

camera_request_snapshot:
  description: Request a camera takes a snapshot
  fields:
    entity_id:
      description: Name(s) of entities to turn on
      example: 'camera.aarlo_front_camera'

camera_request_snapshot_to_file:
  description: Request a camera takes a snapshot and write it to a file
  fields:
    entity_id:
      description: Name(s) of entities to turn on
      example: 'camera.aarlo_front_camera'
    filename:
      description: string (required) where to save the snapshot
      example: 'snapshot.jpg'

camera_request_video_to_file:
  description: Request a camera records a video and write it to a file
  fields:
    entity_id:
      description: Name(s) of entities to turn on
      example: 'camera.aarlo_front_camera'
    filename:
      description: string (required) where to save the video
      example: 'snapshot.mp4'

camera_stop_activity:
  description: Stop all stream activity on a camera
  fields:
    entity_id:
      description: Name(s) of entities to turn on
      example: 'camera.aarlo_front_camera'

camera_siren_on:
  description: Turn on camera siren.
  fields:
    entity_id:
      description: Name(s) of entities to turn on
      example: 'camera.aarlo_front_camera'
    volume:
      description: volume to use
      example: 6
    duration:
      description: duration to turn on for in seconds
      example: 30

camera_siren_off:
  description: Turn off camera siren.
  fields:
    entity_id:
      description: Name(s) of entities to turn off
      example: 'camera.aarlo_front_camera'

camera_start_recording:
  description: Request a camera start recording to cloud
  fields:
    entity_id:
      description: Name(s) of entities to turn on
      example: 'camera.aarlo_front_camera'

camera_stop_recording:
  description: Request a camera stop recording to cloud
  fields:
    entity_id:
      description: Name(s) of entities to turn on
      example: 'camera.aarlo_front_camera'

alarm_set_mode:
  description: Set the mode of a base station.
  fields:
    entity_id:
      description: Name(s) of entities to turn on
      example: 'alarm_control_panel.aarlo_front'
    mode:
      description: mode or schedule to change to
      example: 'home'

alarm_siren_on:
  description: Turn on base station siren.
  fields:
    entity_id:
      description: Name(s) of entities to turn on
      example: 'alarm_control_panel.aarlo_front'
    volume:
      description: volume to use
      example: 6
    duration:
      description: duration to turn on for in seconds
      example: 30

alarm_siren_off:
  description: Turn off base station siren.
  fields:
    entity_id:
      description: Name(s) of entities to turn off
      example: 'alarm_control_panel.aarlo_front'

